--Cleanup
DROP SEQUENCE CONSOLE_ID_SEQ;
DROP SEQUENCE COMPANY_ID_SEQ;
DROP SEQUENCE DEVELOPER_ID_SEQ;
DROP SEQUENCE USER_ID_SEQ;
DROP SEQUENCE TAG_ID_SEQ;

--Order in drops is important to avoid foreign key violations
DROP TABLE USERS_CONSOLES;
DROP TABLE GAMES_CONSOLES;
DROP TABLE USERS_GAMES;
DROP TABLE GAMES_TAGS;
DROP TABLE USERS;
DROP TABLE CONSOLES;
DROP TABLE GAMES;
DROP TABLE DEVELOPERS;
DROP TABLE COMPANIES;
DROP TABLE TAGS;

--Sequence creation for table ids
CREATE SEQUENCE CONSOLE_ID_SEQ START WITH 1;
CREATE SEQUENCE COMPANY_ID_SEQ START WITH 1;
CREATE SEQUENCE DEVELOPER_ID_SEQ START WITH 1;
CREATE SEQUENCE USER_ID_SEQ START WITH 1;
CREATE SEQUENCE TAG_ID_SEQ START WITH 1;

--Main tables creation
CREATE TABLE DEVELOPERS(
  ID      NUMBER(5) PRIMARY KEY,
  NAME    VARCHAR2(30),
  COUNTRY VARCHAR2(20),
  URL     VARCHAR2(100)
);

CREATE TABLE GAMES(
  CODE            VARCHAR2(9),
  TITLE           VARCHAR2(30) UNIQUE NOT NULL,
  DESCRIPTION     VARCHAR2(300),
  MEDIA           VARCHAR2(6) NOT NULL,
  RELEASED_YEAR   NUMBER(4) NOT NULL,
  PRICE           NUMBER(6,2) NOT NULL,
  PLAYERS_NUMBER  NUMBER(2),
  STORAGE_SPACE   VARCHAR2(10),
  RATE            VARCHAR2(1),
  AVERAGE_RATING  NUMBER(4,2),
  DEVELOPER_ID    NUMBER(5) NOT NULL,
  CONSTRAINT GAMES_PK PRIMARY KEY (CODE),
  CONSTRAINT GAMES_DEVELOPERS_FK FOREIGN KEY (DEVELOPER_ID) REFERENCES DEVELOPERS(ID) ON DELETE CASCADE,
  CONSTRAINT GAMES_MEDIA_TYPES CHECK(MEDIA IN ('CD','DVD','UMD','BluRay'))
);

CREATE TABLE COMPANIES(
  ID        NUMBER(5) PRIMARY KEY,
  NAME      VARCHAR2(30),
  FULL_NAME VARCHAR2(100),
  COUNTRY   VARCHAR2(20),
  URL       VARCHAR2(100)
);

CREATE TABLE CONSOLES(
  ID          NUMBER(5) PRIMARY KEY,
  NAME        VARCHAR2(10) NOT NULL,
  FULL_NAME   VARCHAR2(50),
  DESCRIPTION VARCHAR2(300),
  PRICE       NUMBER(6,2) NOT NULL,
  MAX_PLAYERS NUMBER(1) NOT NULL,
  WIRELESS   VARCHAR2(1) DEFAULT 'N' NOT NULL,
  NETWORK     VARCHAR2(1) DEFAULT 'N' NOT NULL,
  HD          VARCHAR2(1) DEFAULT 'N' NOT NULL,
  MEDIA       VARCHAR2(6) NOT NULL,
  COMPANY_ID  NUMBER(5) NOT NULL,
  CONSTRAINT CONSOLES_COMPANIES_FK FOREIGN KEY(COMPANY_ID) REFERENCES COMPANIES(ID) ON DELETE CASCADE,
  CONSTRAINT WIRELESS_YES_NO CHECK (WIRELESS IN ('Y','N')),
  CONSTRAINT NETWORK_YES_NO CHECK (NETWORK IN ('Y','N')),
  CONSTRAINT HD_YES_NO CHECK (HD IN ('Y','N')),
  CONSTRAINT CONSOLES_MEDIA_TYPES CHECK(MEDIA IN ('CD','DVD','UMD','BluRay'))
);

CREATE TABLE USERS(
  ID          NUMBER(5) PRIMARY KEY,
  NAME        VARCHAR2(10) NOT NULL,
  LAST_NAME   VARCHAR2(10) NOT NULL,
  BIRTH_DATE  DATE
);

CREATE TABLE TAGS(
  ID    NUMBER(5) PRIMARY KEY,
  NAME  VARCHAR2(10) UNIQUE NOT NULL
);

--Join tables creation

CREATE TABLE USERS_CONSOLES(
  USER_ID             NUMBER(5) NOT NULL,
  CONSOLE_ID          NUMBER(5) NOT NULL,
  ACQUIRED_DATE       DATE,
  ACQUIRED_CONDITION  VARCHAR2(4) DEFAULT 'NEW' NOT NULL,
  CONSTRAINT USERS_CONSOLES_PK PRIMARY KEY (USER_ID, CONSOLE_ID),
  CONSTRAINT USERS_CONSOLES_USERS_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT USERS_CONSOLES_CONSOLES_FK FOREIGN KEY (CONSOLE_ID) REFERENCES CONSOLES(ID) ON DELETE CASCADE,
  CONSTRAINT CONSOLE_ACQUIRED_CONDITION CHECK (ACQUIRED_CONDITION IN ('NEW', 'USED'))
);

CREATE TABLE USERS_GAMES(
  USER_ID             NUMBER(5) NOT NULL,
  GAME_CODE           VARCHAR2(9) NOT NULL,
  ACQUIRED_DATE       DATE,
  ACQUIRED_CONDITION  VARCHAR2(4) DEFAULT 'NEW' NOT NULL,
  CURRENT_CONDITION   VARCHAR2(8) DEFAULT 'OPENED' NOT NULL,
  GREATEST_HITS       VARCHAR2(1) DEFAULT 'N' NOT NULL,
  CONSTRAINT USERS_GAMES_PK PRIMARY KEY (USER_ID, GAME_CODE),
  CONSTRAINT USERS_GAMES_USERS_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT USERS_GAMES_GAMES_FK FOREIGN KEY (GAME_CODE) REFERENCES GAMES(CODE) ON DELETE CASCADE,
  CONSTRAINT GAME_ACQUIRED_CONDITION CHECK (ACQUIRED_CONDITION IN ('NEW','USED')),
  CONSTRAINT GAME_CURRENT_CONDITION CHECK (CURRENT_CONDITION IN ('OPENED','BRANDNEW')),
  CONSTRAINT GREATEST_HITS_YES_NO CHECK (GREATEST_HITS IN ('Y','N'))
);

CREATE TABLE GAMES_CONSOLES(
  GAME_CODE   VARCHAR2(9) NOT NULL,
  CONSOLE_ID  NUMBER(5) NOT NULL,
  CONSTRAINT GAMES_CONSOLES_PK PRIMARY KEY(GAME_CODE, CONSOLE_ID),
  CONSTRAINT GAMES_CONSOLES_GAMES_FK FOREIGN KEY (GAME_CODE) REFERENCES GAMES(CODE) ON DELETE CASCADE,
  CONSTRAINT GAMES_CONSOLES_CONSOLES_FK FOREIGN KEY (CONSOLE_ID) REFERENCES CONSOLES(ID) ON DELETE CASCADE
);

CREATE TABLE GAMES_TAGS(
  GAME_CODE   VARCHAR2(9) NOT NULL,
  TAG_ID      NUMBER(5) NOT NULL,
  DATE_TAGGED DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT GAMES_TAGS_PK PRIMARY KEY (GAME_CODE, TAG_ID),
  CONSTRAINT GAMES_TAGS_GAMES_FK FOREIGN KEY (GAME_CODE) REFERENCES GAMES(CODE) ON DELETE CASCADE,
  CONSTRAINT GAMES_TAGS_TAGS_FK FOREIGN KEY (TAG_ID) REFERENCES TAGS(ID) ON DELETE CASCADE
);
